### ISSUE TITLE
Return JSON Array of Actions

### ISSUE THREAD

**Issue by MichaelHilton** [GumTreeDiff/gumtree#12]
Hello-
I am totally willing to implement this, I just wanted to get some input about where should be the best place for it.
I could add a function called something like getJSONActions in ActionGenerator?
Perhaps Action should have a "toJSON" method that every action should then implement as well?

Does this sounds like a good plan, or do you have another suggestion?

**Comment by jrfaller** [comment]
Hi Michael,

I think that this is something that is really needed. We also have to think about having something a little generic because we will probably end-up supporting multiple formats (several flavors of JSON, several flavors of XML). I think the best would be to do as Floreal did with tree serializers, you can have a look at it, I think it uses a sort of abstract visitor that is subclassed into several concrete serializers. You can also have a look at the Serializer class in the client module because we could have the same for actions. I will assign floreal to this issue so that he'll be notified and give us his opinion.

**Comment by morandat** [comment]
Definitely ActionSerializers should inherit (maybe not in the canonical sense of the word inherit) the framework of TreeSerializers. I will try to do something about it before the end of the week.

**Comment by MichaelHilton** [comment]
thanks! that would be great!
