### ISSUE TITLE
Dependencies between actions

### ISSUE THREAD

**Issue by jose** [GumTreeDiff/gumtree#122]
Hi,

Given a set of `com.github.gumtreediff.actions.model.Action` objects, is there any way to know whether an action X depends on actions A, B, ...?

--
Best,
Jose

**Comment by jose** [comment]
> you have to precise you definitions of depends on.

In my context/scenario, the definition of dependencies is exactly the same as at compile time. I.e., an action X is considered dependent on an action A if, in order to compile the outcome of action X, action A must also to be applied.

> What are you trying to achieve ?

I want to count the number of _independent changes_ between two trees. For instance, for the following diff
```diff
- Foo foo = new Foo();
+ Bar bar = new Bar();
+ Foo foo = new Foo(bar);
```
there are (according to GumTree) 11 actions, however in practice is only one change (which involves the addition of a new line and the edition of an existing line).

**Comment by monperrus** [comment]
You may be interested in

ClDiff: generating concise linked code differences
https://dl.acm.org/citation.cfm?id=3238219
https://github.com/FudanSELab/CLDIFF

**Comment by jrfaller** [comment]
Yes in ClDiff you will find dependencies relations. It is not formally coded in GumTree but it should be straightforward to code.

Basically action b depends on a action a : 
- if it is applied at a location that has been added by action a
- if it is applied on the same parent than action a and come after in the sequence

I don't see any other syntactic dependence, but I might be missing something? Maybe for deletions, a deletion can only be applied only on a leaf node so 
- if it deletes a node that has been made childless as a result of action a? but this is not correct because if they are three children the delete of the node is dependent on the three deletes of the children... I am not sure how to treat this case.

Then by building a graph it is easy enough to search for the connected components, the number of connected components being the number of independent changes, this is pretty much what is doing the ActionClusterFinder but with other dependency definitions.

**Comment by jose** [comment]
Thanks @monperrus and @jrfaller.

Another related work is the [Interactively Decomposing Composite Changes to Support Code Review and Regression Testing](https://ieeexplore.ieee.org/abstract/document/8029599/) which
> (1) interactively decomposing composite changes into atomic changes, (2) building related change subsets using program dependence relationships without syntactic violation, ...

**Comment by monperrus** [comment]
Thanks a lot, interesting. Ping @bissyande  @martinezmatias @zongxingyu

**Comment by monperrus** [comment]
See also


      Untangling Composite Commits Using Program Slicing

<https://www.researchgate.net/publication/328096791_Untangling_Composite_Commits_Using_Program_Slicing>
