### ISSUE TITLE
JdtTreeGenerator: Unable to extract varargs property from SingleVariableDeclaration nodes

### ISSUE THREAD

**Issue by tsantalis** [GumTreeDiff/gumtree#138]
Hello,
I am using TreeContext to generate method signatures.
There is a varargs parameter `String... options` in one of the method declarations.
However, the TreeContext looks as follows:
```
(44 "SingleVariableDeclaration" "" ((763 17)) (
                (43 "SimpleType" "String" ((763 6)) (
                    (42 "SimpleName" "String" ((763 6)) ())
                (42 "SimpleName" "options" ((773 7)) ())
```
The type is a SimpleType with String as value.
I cannot find a way to get the varargs property.
In Eclipse JDT SingleVariableDeclaration, it is a boolean property.
Is there a way to get the varargs property value?

**Comment by jrfaller** [comment]
Hi Nikolaos!

You're right, varargs does not seem to have dedicated AST nodes... Instead there is a boolean property `isVarargs()` (https://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FSingleVariableDeclaration.html). To have it in the AST I have to forge dedicated nodes that will be inserted in these cases when traversing the JDT tree, do you have an idea of the AST I should generate?

**Comment by tsantalis** [comment]
I noticed that `TreeContext` and `Tree` have a `metadata` property, which is always null or empty.
I don't know what is the use of the metadata property, but it seems like a good place to store AST node properties, such as varargs in SingleVariableDeclaration.
It doesn't make sense to make a separate Tree node for varargs, because it does not correspond to any Eclipse JDT ASTNode type.

**Comment by tsantalis** [comment]
Here is the list of all boolean ASTNode properties:
SingleVariableDeclaration.VARARGS_PROPERTY
MethodRefParameter.VARARGS_PROPERTY
SimpleName.VAR_PROPERTY **(JLS10 API)**
WildcardType.UPPER_BOUND_PROPERTY
ImportDeclaration.STATIC_PROPERTY
LambdaExpression.PARENTHESES_PROPERTY **(JLS8 API)**
ModuleDeclaration.OPEN_PROPERTY **(JLS9 API)**
ImportDeclaration.ON_DEMAND_PROPERTY
TypeDeclaration.INTERFACE_PROPERTY
MethodDeclaration.CONSTRUCTOR_PROPERTY

**Comment by jrfaller** [comment]
Mmm I think I will have to modifiy the AST because currently `void foo(String... args);` has no difference with `void foo(String args);`, which is bad. The metadata property is only a facility to place runtime properties on the nodes, but is not intended to be diffed wih the tree.

Thanks for the list of properties. Some of them have no influence on the diff (such as MethodDeclaration.CONSTRUCTOR_PROPERTY), therefore cause no trouble fine. Other should have an influence (like ImportDeclaration.STATIC_PROPERTY). I will have to try them all and see which kind of AST I have to generate.

**Comment by monperrus** [comment]
FYI, varargs works out of the box in Gumtree-spoon: https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/test/java/gumtree/spoon/AstComparatorTest.java#L1663

**Comment by jrfaller** [comment]
Yes indeed it would do the trick!

**Comment by jrfaller** [comment]
Mmmm this one is trickier than I though. I have a solution for simple varargs properties such as `String` vs `String...` following the solution of @tsantalis. However the solution does not work with mixtures of generic types and varargs for instance `List<String>` vs `List<String>...`. For this latter case this solution does not work because the type is itself a tree such as:

```
ParameterizedType [28,40]
                    SimpleType [28,32]
                        SimpleName: List [28,32]
                    SimpleType [33,39]
                        SimpleName: String [33,39]
```
Therefore not easy to decide where to add the `...` (adding it on string or list both lead to a cumbersome diff). Maybe another solution would be to enclose the type subtree into a VarargSimpleVariableDeclaration node?
