### ISSUE TITLE
False positive diff

### ISSUE THREAD

**Issue by Symbolk** [GumTreeDiff/gumtree#156]
I found the jar built from the latest develop branch reports one obvious false positive diff, which is not reported by the latest release 2.1.2 (https://github.com/GumTreeDiff/gumtree/releases/tag/v2.1.2).

The two files to diff:
From https://github.com/google/guava/commit/dcf63a6c97dfde2946c201d1595f33469d25c1a4#diff-429137497252fd8358afec4529f16e43

[files.zip](https://github.com/GumTreeDiff/gumtree/files/3447346/files.zip)

Latest develop branch:
![image](https://user-images.githubusercontent.com/14107297/62139443-ee005980-b31b-11e9-9c1b-b28ea72b0edb.png)

Release 2.1.2:
![image](https://user-images.githubusercontent.com/14107297/62139478-ff496600-b31b-11e9-922e-dfc38482ce74.png)

**Comment by jrfaller** [comment]
Hi and thanks for the report. I know why it's there, it's because we have modified some stuff in the bottum up matcher (not pruning the tree before launching the optimal algorithm) and it can be resolved by using the gumtree-simple matcher instead of classic gumtree. It will be gumtree's next default matcher after some more testing ;)

**Comment by jrfaller** [comment]
Duplicate #150
