### ISSUE TITLE
Modifications on Extends and Implements are not detected  

### ISSUE THREAD

**Issue by alkalinan** [GumTreeDiff/gumtree#157]
Hello, 

when using gumtree (swingdiff or webdiff) on this case : 
<img width="1116" alt="p" src="https://user-images.githubusercontent.com/19858911/63388200-f0e4ec00-c3a7-11e9-98cb-08e868743029.png">
no change is detected... However there is an obvious change on the class A declaration by using extends or implements. 

When I look at the ITree and TreeContext, it seems that Gumtree is extracting all simpleTypes, ParametrizeType, and typeParameters without knowing if there are part of the **extends** or the **implements** declarations.

**Comment by monperrus** [comment]
Could you try with https://github.com/SpoonLabs/gumtree-spoon-ast-diff/?

**Comment by alkalinan** [comment]
Hi, unfortunately no because I am using Gumtree v2.1.3 which includes TreeDelete and TreeInsert. There are not yet implemented in the current version of gumtree-spoon. 

Or do you want me to try to see if the behavior is the same ?

**Comment by jrfaller** [comment]
I believe @monperrus is asking you to see if the behavior is the same. I know what is causing the problem : extends / implements is not part of the Jdt AST, it's only a property on the type node, therefore I have to rewrite the AST to make this token explicit. However it is a little tedious since there can be both extends and implements on a type definition.

**Comment by monperrus** [comment]
I confirm that:

* gumtree-spoon depends on gumtree 2.1.2 and not on 2.1.3
* gumtree-spoon well implements the extends / implements detection

**Comment by jrfaller** [comment]
BTW, working well in GumTree now.
