### ISSUE TITLE
Lost block of Jdtgenerator

### ISSUE THREAD

**Issue by chijianlei** [GumTreeDiff/gumtree#159]
I have tested AST generation of Jdtparser. However, it seems that AST created by Jdtgenerator loses some blocks of the source code. 

Attached is my testing code, the Jdtgenerator cannot identify the whole block of the function "public static AccountInstance getInstance". I have checked the dot graph, only one block leaf node is under the MethodDeclaration node. There should be a large subtree linked to this block node but it misses.

I'm not sure it causes by JDTparser or by gumtree. I will try to use Jdtparser independently.

[AccountInstance.zip](https://github.com/GumTreeDiff/gumtree/files/3552910/AccountInstance.zip)

**Comment by jrfaller** [comment]
By using javaparser it seems the error comes from a syntax error, line 16, there is no condition for the `else if` (try replacing it by` else if (true)`, however it would be nice that JdtTreeGenerator report a syntax error instead of automatically recovering it. I will see if I can do something. In the meantime, don't hesitate to try javaparser when you have doubt with some java files.
