### ISSUE TITLE
C++ Comments incorrectly flagged as added/deleted

### ISSUE THREAD

**Issue by csiefer2** [GumTreeDiff/gumtree#246]
The comments in these two files are unchanged and yet they are flagged as being added/deleted.  The output of gumtree parse for those commented lines are identical, so I suspect srcML isn't the source of the problem here.

I'll note that things work correctly on (much) smaller versions of the same file (e.g. if I remove most of the code and leave the comments).

I've attached both the raw C++ files to diff, their output from gumtree parse and the htmldiff output.

[files.tar.gz](https://github.com/GumTreeDiff/gumtree/files/7100932/files.tar.gz)

**Comment by csiefer2** [comment]
gumtree SHA 90ddad36c69544eefb85815f204e490bdc95fbc0

**Comment by csiefer2** [comment]
When I use git integration (since these file are from our repo), I see the same error with monaco, but not monaco-native, interestingly.

**Comment by jrfaller** [comment]
Hi Christopher!

I looked into your case, and it's a classic bad case for the GumTree default code differ. Since the AST of the file is huge, some optimizations are deactivated to avoid a very high running time and lead to the comment not being recognized. We have a differ designed for these kind of cases and you can try it out with the following command :

`gumtree webdiff MueLu_ParameterListInterpreter_def_old.hpp MueLu_ParameterListInterpreter_def_new.hpp -m gumtree-simple`

I looked into the result and it seems to handle your case adequately.

Frankly for huge C++ files I would personally use this matcher all the time ;). You can also have the best of both world by using the `-m gumtree-hybrid` differ that adapts itself depending on the size of the AST.

Let me know if you manage to use it.

Cheers.

**Comment by csiefer2** [comment]
Works correctly!  Thanks!
