### ISSUE TITLE
Slow parsing of JS files

### ISSUE THREAD

**Issue by intumwa** [GumTreeDiff/gumtree#259]
I use GumTree to diff JS scripts with dozen lines of code and it takes about a second to give me the results. But when I try files with +1000 lines of code like the [files in this gist](https://gist.github.com/intumwa/b9dc2b355e479d1ddda79fdb01dff7ca), GumTree takes 20 minutes to give me the results. Is this a known issue with GumTree? Or there is a way to fix it?

Below is my code snippet (I am running the code on a Mac):

```Tree src = TreeGenerators.getInstance().getTree(srcFile).getRoot();
Tree dst = TreeGenerators.getInstance().getTree(dstFile).getRoot();
Matcher defaultMatcher = Matchers.getInstance().getMatcher();
MappingStore mappings = defaultMatcher.match(src, dst);
EditScriptGenerator editScriptGenerator = new SimplifiedChawatheScriptGenerator();
EditScript actions = editScriptGenerator.computeActions(mappings);

System.out.println(mappings.size());
System.out.println(actions.size());

**Comment by jrfaller** [comment]
Hello!

To be honest the JS generator has not been tested much. It is based upon Mozilla Rhino's lib. Could you try monitoring the code to see if the performance drop is due to Rhino's parser (I believe this is the case). Another drawback of Rhino is that it's not capable of handling recent JS code.

If it's important for your research to be capable of handling JS correctly, maybe it would be a good thing to introduce a new generator. I've heard good things of the parser in graaljs (https://github.com/oracle/graaljs/tree/master/graal-js/src/com.oracle.js.parser/src/com/oracle/js/parser) so this could be a promising lead. Another possibility would be to use a js parser outputting XML that would then be loaded into gumtree.

Cheers.

**Comment by intumwa** [comment]
Hello!

Thanks for your quick response. I'll try the parse in graaljs and see if there is a better JS parser that I can use. If all goes well I'll share it with you.

Cheers.

**Comment by jrfaller** [comment]
That's a good idea. Maybe you can try to benchmark the time it takes to parse your files
- using RhinoJS (you can see the related code in GumTree)
- using GraalJS (to see if it's faster)

WDYT?

**Comment by intumwa** [comment]
It's a good idea indeed. I'm looking at the code in GumTree and will let you know once I manage to benchmark both RhinoJS and GraalJS.

**Comment by intumwa** [comment]
Hello, I ran into regex issues with RhinoJS on many of the JS scripts (ES syntax errors, maybe as you said RhinoJS doesn't keep up with recent ES code)  and I wasn't able to run GraalJS as I couldn't figure out how. So, since my objective was to know how much a script has changed, I decided to encode the content with Base64 and calculate the Levenshtein distance between the encoded content. Sorry, I wasn't of much use here 😔

**Comment by jrfaller** [comment]
Hey no problem at all :-) 

We can come back to this if you need more qualitative information about the changes!

**Comment by jrfaller** [comment]
Hi @intumwa 

FYI I added JS support with two new parser, one based upon acorn and the other based upon tree-sitter. TypeScript should also be easy to integrate since it is also in tree-sitter.
