### ISSUE TITLE
Different output for very similar Python and R programs

### ISSUE THREAD

**Issue by nicolaskruchten** [GumTreeDiff/gumtree#263]
Hello,

Thank you for open-sourcing this excellent tool, which I am starting to use in my research, and plan to cite! I've encountered some unusual output when comparing R files, which can be replicated with the commands below using version 3.0.0:

```bash
echo 'f() + g()' > f1.R
echo 'f() + g() + h()' > f2.R   
gumtree textdiff f1.R f2.R
```

<details>
<summary>Click for output</summary>
<pre>
===
match
---
ID: g [6,7]
ID: g [6,7]
===
match
---
CALL: f [0,3]
CALL: f [0,3]
===
match
---
ID: f [0,1]
ID: f [0,1]
===
match
---
SEQUENCE [0,10]
SEQUENCE [0,16]
===
match
---
PLUS: + [0,10]
PLUS: + [4,5]
===
match
---
CALL: g [6,9]
CALL: g [6,9]
===
insert-node
---
PLUS: + [0,16]
to
SEQUENCE [0,10]
at 0
===
move-tree
---
PLUS: + [0,10]
    CALL: f [0,3]
        ID: f [0,1]
    CALL: g [6,9]
        ID: g [6,7]
to
PLUS: + [0,16]
at 0
===
insert-tree
---
CALL: h [12,15]
    ID: h [12,13]
to
PLUS: + [0,16]
at 1
</pre>
</details>

Based on the output, it looks like the parse tree is being built from the right, so the `f() + g()` tree is being moved below a new right-most `+` node, which seems strange to me. I would expect the R output to be quite similar to the output for the same files using the Python parser, say (just replace `.R` with `.py` above for example).

```bash
echo 'f() + g()' > f1.py
echo 'f() + g() + h()' > f2.py   
gumtree textdiff f1.py f2.py
```

<details>
<summary>Click for output</summary>
<pre>
===
match
---
atom_expr [0,3]
atom_expr [0,3]
===
match
---
arith_expr [0,9]
arith_expr [0,15]
===
match
---
operator: + [4,5]
operator: + [4,5]
===
match
---
file_input [0,10]
file_input [0,16]
===
match
---
trailer [1,3]
trailer [1,3]
===
match
---
trailer [7,9]
trailer [7,9]
===
match
---
name: f [0,1]
name: f [0,1]
===
match
---
name: g [6,7]
name: g [6,7]
===
match
---
simple_stmt [0,10]
simple_stmt [0,16]
===
match
---
atom_expr [6,9]
atom_expr [6,9]
===
insert-node
---
operator: + [10,11]
to
arith_expr [0,9]
at 3
===
insert-tree
---
atom_expr [12,15]
    name: h [12,13]
    trailer [13,15]
to
arith_expr [0,9]
at 4
</pre>
</details>

Is this intentional? If not, and if I was to submit a PR to change it, would you accept such a PR? From a cursory look, it seems like the relevant file is in https://github.com/GumTreeDiff/gumtree/tree/main/gen.antlr3-r right?

**Comment by jrfaller** [comment]
Hi @nicolaskruchten and thanks for the kind words!

I second your opinion that it is strange. However the mastermind behind this R parser is @morandat so maybe he has an explanation?

FYI I just landed a tree-sitter based R parser, so you might wanna look into it https://github.com/GumTreeDiff/tree-sitter-parser

However, you'll need the HEAD version of GumTree and install tree-sitter-parser, but it could be worth it as the tree-sitter parsers are usually very good (but I have not tested this one).

If you want to make a PR to our AntLR parser, you have the right module, but I warn you that this parser is currently unmaintained.

Also, don't hesitate to drop me a mail about your research project.

Cheers!

**Comment by nicolaskruchten** [comment]
Upon further reflection, I can see a case for either approach here... I think I was surprised by the R output mostly because I'd started with the Python case first. Had I done things in the opposite order, this issue might well have been entitled "Strange output for Python files"!

In the Python case, the tree that gumtree operates on for `f() + g() + h()` is basically a flattened `term(atom_expr, operator, atom_expr, operator, atom_expr)` (and this seems to be true so long as the `operator`s have the same precedence level). 

In the R case, the tree that gumtree operates on for `f() + g() + h()` is a strictly binary `plus(plus(call, call), call)` which also does make sense given the left-to-right processing of `+`.

It's hard to say which is "more correct". In terms of interpreting the edit scripts as expressing "developer intent" (which is what I'm hoping to use gumtree to approximate!) I think it's surprising to see `move-tree` when the developer might think "all I did was add something!" but it's certainly true that from an execution perspective, a tree has been moved. The Python approach here also yields smaller edit scripts in this case. 

That said, for R specifically, it's now very common in data science to use the non-built-in `%>%` pipe operator to "add a processing stage to a pipeline" which in effect does add a level of nesting to the call tree, but the whole point of the pipe operator is to hide this from the user, or at least make them less aware of it. Then there is the new built-in base-R `|>` pipe operator, which might be easily modelled in a parse tree like `+` or `%>%` yielding `op(g,f)` or might be modelled such that `g |> f` yields `f(g)`, which I understand is exactly how the R interpreter treats it 🤷 

Regardless which is "more correct" in general, it might be considered a bit awkward that gumtree returns different outputs here for very similar programs in different languages... Is there a way for me to provide a language-specific parse tree or parser command from the command line, so that I can control this myself? Or should I write some Java code to do this?

Thanks for the offer to correspond about my research BTW, I will email you :)

**Comment by nicolaskruchten** [comment]
After a bit more research, I think it's worth mentioning that `parso`, which https://github.com/GumTreeDiff/pythonparser is based on, seems to generate a Concrete Syntax Tree (CST) rather than an AST, per https://github.com/davidhalter/parso/issues/164

I was able to build a little script that outputs the XML format that `gumtree` expects using Python's built-in `ast` module, and use that as a replacement for https://github.com/GumTreeDiff/pythonparser such that the output of `gumtree` for both R and Python looks much more similar. I can force `gumtree` to use it via `gumtree -C -C gt.pp.path path/to/script` which is nice :)

My script isn't totally generalized or well-tested but it will meet my needs for the moment. I'm happy to share it if it's a useful alternative to https://github.com/GumTreeDiff/pythonparser for anyone!

**Comment by jrfaller** [comment]
Hi!

You are right.

I tried to move from ASTs towards CSTs as much as possible. Fun fact, the previous `pythonparser` used the `ast` module. There is even a pull request from the amazing people at JetBrains research with a polished implementation (https://github.com/GumTreeDiff/pythonparser/pull/9) that I have to integrate as a separate repository to avoid messing with the `parso` implementation. You can look into it, if it's useful to you I can try to give this a higher priority.

In short, I prefer to use CSTs, because sometimes ASTs lack important information that you really need to see in the diff. Like with typical ASTs you will have for `a + b` the following AST:

~~~
binary_expr
  identifier (label = a)
  identifier (label = b)
~~~

Therefore you won't be able to even see a change if the expression becomes `a - b`.

I personally prefer to have this representation

~~~
binary_expr
  identifier (label = a)
  binary_operator (label = +)
  identifier (label = b)
~~~

Which is not the product of a typical CST, that are more likely something like 

~~~
binary_expr
  identifier (label = a)
  + (label = +)
  identifier (label = b)
~~~

Philosophically, the AST representation might be legit, as there were no structural change, therefore the diff is blank. But I cannot really see a situation where a developer would want this behavior. So my take on this problem is that we need something between the CST and the AST that is carefully crafted to foster program change comprehension (and this can be very subjective). I am currently working on this problem, but this is a hard one. So far the idea is to provide a simple rewriting configuration language that allows tuning the CSTs without hassle, but even with this it's not easy to know what are the cool rewrite opportunities for a given grammar. We are investigating whether or not analyses of the grammars with some heuristics could yield some useful rewrite opportunities.

**Comment by nicolaskruchten** [comment]
Ah, that's super helpful, thank you! Thanks for pointing out https://github.com/GumTreeDiff/pythonparser/pull/9... it's a much better version of what I had started, and I can happily use it.

I'm going to close this issue now as there doesn't seem to be anything concrete to do, but I thank you for helping me think through this and sharing your current ideas about CST vs AST. For what it's worth, what you're describing does match my intuition about a nice way forward, and I agree it seems very challenging!

One idea I had as a result of thinking about this has been captured in https://github.com/GumTreeDiff/gumtree/issues/265, which I'm happy to work on if it's of interest.
