### ISSUE TITLE
seems confused edit script

### ISSUE THREAD

**Issue by xzm2000** [GumTreeDiff/gumtree#279]
Hi! I am confused by the edit script in these two java files by `gumtree-simple`. (Because github can only upload `.txt`, I changed the name from `.java` to `.txt`)
[old.txt](https://github.com/GumTreeDiff/gumtree/files/8506061/old.txt)
[new.txt](https://github.com/GumTreeDiff/gumtree/files/8506062/new.txt)

My command is: `gumtree webdiff old.java new.java -m gumtree-simple`
I didn't use `gumtree` because the unexpected change for `public class KeyedObjects2D`

The result is a little confused, why move and delete here?

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/42742291/163819107-a99bbd72-8157-49d6-bdee-09471fdc108b.png">

**Comment by jrfaller** [comment]
Thanks for the report. It's due to a corner-case where there is only one candidate block and the default similarity threshold is too low by default (a little too optimistic I realize for these cases). It no longer does it when setting a larger value : `gumtree webdiff old.java new.java -m gumtree-simple -M bu_minsim 0.5`
