### ISSUE TITLE
Generate source code from a given GumTree AST

### ISSUE THREAD

**Issue by ChrisTimperley** [GumTreeDiff/gumtree#28]
Is it possible to generate valid source code (not necessarily the original source code) from a GumTree AST? In particular, I'm interested in doing this for C. Ideally, it would be great if I could provide a JSON or XML GumTree AST file, to the `gumtree` binary, together with the language that the AST belongs to.

Thanks!

**Comment by ChrisTimperley** [comment]
In case anyone else is interested in doing something similar, I've whipped together a quick Python representation of the CGum ASTs: https://github.com/ChrisTimperley/PythonCGum

**Comment by jrfaller** [comment]
Hi!

You mean that you want a pretty printer, that takes as input a gumtree representation of a given AST and produces as output a source code file?

Someone tried to implement something like that for Java but it was difficult because there was some case of ambiguity (a same AST construct that could give birth to two distincts language constructs)... Maybe it is possible in C, but we did not plan to implement it anytime soon.

**Comment by ChrisTimperley** [comment]
Yeah, exactly. Or better yet, just it pretty-prints the sub-tree rooted at a given node (if possible).

Ah, that's interesting. It doesn't really need to be perfect, nor to produce the original source code. It just needs to be fairly consistent. That's fair enough. I should be able to whip up the node I need today :-) Thanks anyway. The tool is great!
