### ISSUE TITLE
Formal definition of edit script language

### ISSUE THREAD

**Issue by ChrisTimperley** [GumTreeDiff/gumtree#38]
Please can you provide a more formal definition of the edit script operations and their encodings (with respect to any action serialiser), similar to the (incredibly useful) language definition for [DUL](http://diffxml.sourceforge.net/dul/dul.html). In particular, please could you clarify the node numberings used in the edit script operations, and if/how the order of operations affect the result?

At present time, it looks as if the output for certain operations is inconsistent, but without a clear, formal definition of the language, I can't be sure (and I can't use GumTree for my research until that point).

**Comment by jrfaller** [comment]
Hi Christopher,

Thanks for the feedback. It is highly possible that the edit script serializer is not entirely correct w.r.t. to node ids or positions because it has not been tested extensively.

Normally the edit script is formalized in our ASE paper you can read it to better understand. Maybe if you have a (small) case with a problem, you can attach the files here and I will take a look at it.

**Comment by ChrisTimperley** [comment]
I'll put together a few unit tests today on my fork to test whether the output matches what I'm expecting, then I'll add a short description here, together with a quick definition of the edit operations, based on the ASE paper.

**Comment by ChrisTimperley** [comment]
I ended up finding a slightly simpler way around the problem (in theory). I just need to use the mappings to work out the IDs of the nodes of interest in P and P', and from there I can do all kinds of clever analyses (some of which use the mappings to simplify things).

**Comment by ChrisTimperley** [comment]
Accepting this pull request would add the functionality required to fix these problems (in a pre-processing stage): https://github.com/GumTreeDiff/gumtree/pull/21
