### ISSUE TITLE
Matcher algorithms

### ISSUE THREAD

**Issue by onhate** [GumTreeDiff/gumtree#49]
Hi,

I could not find any documentation with regarding the Matchers, I would like to know about performance and why the results may differ from one to another.

I've been running the `Matchers.getInstance().getMatcher(src, dst)` and it always returns ZsMatcher as default, but this algorithm in some cases enters in infinite loop and never finishes.

I can provide more details about the scenario that ZsMatcher enters in infinite loop, but by now I would like to have more information about the available algorithms to help me decide which one to use.

Thanks.

**Comment by jrfaller** [comment]
Hi!

Thanks for reporting an issue about GumTree.

This is really strange, `Matchers.getInstance().getMatcher(src, dst)` should return an instance of `ClassicGumtree`, and not ZsMatcher. Can you provide me the code to reproduce the problem, against the latest commit on the develop branch? 

ClassicMatcher is the only (almost 😉) production ready matcher furnished in GumTree, all the others are only implemented for evaluation purpose. However if there is a infinite loop in `ZsMatcher`, 
I am really interested about the test case since this matcher is used under the hood by `ClassicGumtree`.

Cheers!

**Comment by onhate** [comment]
Thanks for you response @jrfaller 

It is possible that `Matchers.getInstance().getMatcher(src, dst)` is returning ClassicGumtree but calling ZsMatcher, I thought it was returning just ZsMatcher because that's what I see on stacktrace when it goes infinite loop.

using these files (I know they are very peculiar).
https://gist.github.com/onhate/21bd5764fcf333051d05e221e7063a5e

and this snippet

```
            TreeContext src = Generators.getInstance().getTree(left.toString());
            TreeContext dst = Generators.getInstance().getTree(right.toString());

            Matcher matcher = Matchers.getInstance().getMatcher(src.getRoot(), dst.getRoot());
            matcher.match();

            TreeClassifier classifier = new RootAndLeavesClassifier(src, dst, matcher);
```

**Comment by jrfaller** [comment]
OK thanks for the files!

The problem seems to come from the variable LZD containing a binary string because when I remove it, it works like a charm.

I am not sure though why it's a problem for ZsMatcher, unless it comes from the levenstein distance that is computed under the hood.

**Comment by jrfaller** [comment]
Actually, the method used to return label similarity is this one : 

`return 1D - StringMetrics.qGramsDistance().compare(n1.getLabel(), n2.getLabel());`
