### ISSUE TITLE
One change is reported in the DIFF output, but it is not reported in the JSON variant...

### ISSUE THREAD

**Issue by jawilliam** [GumTreeDiff/gumtree#64]
Hi Guys,

I am collecting GumTree’s deltas over C# file pairs. I started by parsing the JSON output, but I am needing further information that is not available for this variant (e.g., label of each involved element). To do that, I am getting the DIFF output now and completing the information for the existing delta (the JSON initially stored). However, I have a case where the DIFF variant reports a change (move expr(853) to expr_stmt(1220)) that was not reported with the JSON variant.

I am moving to store the DIFF delta instead of the JSON one, but I am reporting this problem for your consideration.

Regards, Guillermo.

PD: I am attaching the revision pair.

[RevisionPair.zip](https://github.com/GumTreeDiff/gumtree/files/1209541/RevisionPair.zip)

**Comment by jrfaller** [comment]
Strange, using latest GumTree version and your archive, I obtain the exact same diff (8 insert and 1 update). Maybe this was due to a threshold difference. Don't hesitate to reopen the bug if it happens again.

**Comment by jawilliam** [comment]
Ok, jrfaller.

I finally conducted my studies over the DIFF variant, but I will be reporting more issues if I find them. You have done a good work here.

By the way, it has been longer since I shared you my interest to customize GumTree in some ways:
1) Execute it over a different AST-technology for C#. For example:
   a. Roslyn instead the current SrcML.
   b. SrcML's AST enriched with additional information.

2) Intercepting the matching or the difference phases (before it starts, when it is on going, and after it finished).

As GumTree already supports different parser technologies, I think at least the first one seems doable. But, I do not how, nor if the second one is possible too. In any case, I would appretiate so much your guidance or help. Is that possible?

Regards.

**Comment by jrfaller** [comment]
Hi!

I definitively think that having a better parser than srcML, such as Roslyn would be very nice, since is not Java, it would require to code a native tool that produce XML out of a cs file that would be launched under the hood by GumTree and converted to GumTree's internal format. This is how we do for srcml, C and python for instance.

Regarding your idea to place hooks on the matching phase, I did not think of that but it seems possible to do, but I am curious to know why do you think it can be useful? Perhaps to add pre or post processing?

In any case, if you want to try to add features to GumTree, I will help you.

Cheers!
