### ISSUE TITLE
Please specify the bug in ActionGenerator("//FIXME not sure why :D")

### ISSUE THREAD

**Issue by Symbolk** [GumTreeDiff/gumtree#90]
Hi there,

I am currently developing something in gumtree develop branch, but I see _" //FIXME not sure why :D"_ in ActionGenerator.java, which seems to be an unfixed bug but I cannot figure what it is.

Therefore, can you illustrate the bug in details? An example will be greatly appreciated. @jrfaller

**Comment by jrfaller** [comment]
Hi!

I think I will remove this comment, originally I put it there because the code of the original algorithm I implemented were not working I I recall correctly, therefore I had to add this lines to make it work, but I am confident with current implementation that has been extensively tested, so it's safe to remove this comment

**Comment by Symbolk** [comment]
Great! And I have not encountered bugs around the comment.
